import { z } from 'zod';
import { RUN_EXPORT_TRUNCATED_HEADER } from '@mmt/contracts';
import * as contract from '@mmt/contracts/schemas';
import {
  adminUserCreateSchema,
  adminUserPatchSchema,
  adminUserQuerySchema,
} from '../../domain/adminUserValidation.js';
import {
  auditEventQuerySchema,
  projectAuditEventQuerySchema,
} from '../../domain/auditValidation.js';
import {
  jobRetryRequestSchema,
  runCheckpointCreateSchema,
  runCheckpointListQuerySchema,
} from '../../domain/checkpointValidation.js';
import { repositoryFilesSchema } from '../../domain/codeSourceValidation.js';
import {
  commentCreateSchema,
  commentListQuerySchema,
  commentUpdateSchema,
} from '../../domain/commentValidation.js';
import {
  artifactDigestQuerySchema,
  datasetFileListQuerySchema,
  datasetFileTreeQuerySchema,
  datasetVersionRequestSchema,
} from '../../domain/datasetContentValidation.js';
import {
  taskCreateSchema,
  taskHistoryQuerySchema,
  taskLaunchSchema,
  taskPatchSchema,
} from '../../domain/experimentTaskValidation.js';
import {
  metricGroupsRequestSchema,
  metricSeriesRequestSchema,
} from '../../domain/metricSeries/metricSeriesValidation.js';
import {
  modelAliasAssignmentSchema,
  modelAliasEventQuerySchema,
  modelAliasProtectionInputSchema,
  modelAliasProtectionQuerySchema,
  modelAliasRemovalSchema,
} from '../../domain/modelAliasValidation.js';
import {
  automationExecutionCreateSchema,
  automationExecutionQuerySchema,
  automationRuleOwnerSchema,
  modelAutomationRuleSchema as automationRuleCreateSchema,
  modelAutomationToggleSchema,
} from '../../domain/modelAutomationValidation.js';
import {
  modelVersionEvaluationQuerySchema,
  runDownstreamQuerySchema,
} from '../../domain/modelEvaluationValidation.js';
import {
  notificationChannelCreateSchema,
  notificationChannelPatchSchema,
  notificationDeliveryQuerySchema,
  notificationRuleCreateSchema,
  notificationRulePatchSchema,
} from '../../domain/notificationValidation.js';
import {
  promotionEvaluationQuerySchema,
  promotionPolicyCreateSchema,
  promotionPolicyOwnerSchema,
  promotionPolicyPatchSchema,
  promotionPolicyQuerySchema,
} from '../../domain/promotionPolicyValidation.js';
import {
  parameterImportanceRequestSchema,
  runAnalysisTableRequestSchema,
} from '../../domain/runAnalysisValidation.js';
import { operationsAlertQuerySchema } from '../../domain/operationsAlerts.js';
import { runNoteUpdateSchema } from '../../domain/runNote.js';
import {
  mediaCompareSchema,
  mediaTableQuerySchema,
  runMediaCreateSchema,
  runMediaListQuerySchema,
} from '../../domain/runMediaValidation.js';
import { runResumeRequestSchema } from '../../domain/runResume.js';
import {
  artifactPresenceCheckSchema,
  syncBatchSchema,
  syncRunCreateSchema,
} from '../../domain/runSyncValidation.js';
import {
  savedViewCreateSchema,
  savedViewListQuerySchema,
  savedViewPatchSchema,
} from '../../domain/savedViewValidation.js';
import {
  serviceAccountCreateSchema,
  serviceAccountTokenCreateSchema,
  serviceAccountUpdateSchema,
} from '../../domain/serviceAccountValidation.js';
import {
  storageBackendCreateSchema,
  storageBackendPatchSchema,
  storageSettingsSchema as storageSettingsUpdateSchema,
} from '../../domain/storageBackendValidation.js';
import {
  sweepCancelSchema,
  sweepCreateSchema,
  sweepListQuerySchema,
  sweepPatchSchema,
  sweepTrialQuerySchema,
} from '../../domain/sweepValidation.js';
import {
  targetCheckClaimSchema,
  targetCheckCompleteSchema,
} from '../../domain/targetCheckValidation.js';
import {
  codeVersionSchema as codeVersionCreateSchema,
  completeSchema,
  datasetCreateSchema,
  heartbeatSchema,
  jobCreateSchema,
  logBatchSchema,
  metricBatchSchema,
  modelCreateSchema,
  modelVersionSchema as modelVersionCreateSchema,
  nameSchema,
  namedEntitySchema,
  pluginCreateSchema,
  pluginPatchSchema,
  projectCreateSchema,
  projectPatchSchema,
  roleAssignmentSchema,
  runCreateSchema,
  runPatchSchema,
  targetPatchSchema,
  targetSchema,
  tokenCreateSchema,
  userSearchQuerySchema,
  uuidSchema,
  workerClaimSchema,
  workerLogSchema,
  workerMetricSchema,
  workerResumeSchema,
} from '../../domain/validation.js';
import { workerOutputsSchema } from '../../domain/workerOutputValidation.js';
import { artifactMediaInfoQuerySchema } from '../../routes/artifactMediaInfoRoutes.js';
import {
  artifactCatalogQuerySchema,
  artifactTreeQuerySchema,
  runArtifactQuerySchema,
} from '../../routes/artifactRoutes.js';
import {
  PART_SHA256_HEADER,
  uploadCreateSchema,
  uploadListQuerySchema,
} from '../../routes/artifactUploadRoutes.js';
import {
  changePasswordSchema,
  developmentLoginSchema,
  localLoginSchema,
} from '../../routes/authRoutes.js';
import { pluginDatasetImportSchema, pluginDatasetSearchSchema } from '../../routes/pluginRoutes.js';
import {
  runComparisonCsvQuerySchema,
  runComparisonSchema as runComparisonRequestSchema,
  runQuerySchema,
} from '../../routes/runRoutes.js';
import { runSearchSchema } from '../../routes/runSearchRoutes.js';
import { MAX_DATASET_VERSION_BODY_BYTES, SYNC_BATCH_MAX_BYTES } from '../requestBodyLimits.js';
import {
  GLOBAL_ADMIN,
  PROJECT_ADMIN,
  PROJECT_VIEWER,
  WORKER,
  projectEditor,
  routeError,
  type NativeRoute,
  type NonJsonContent,
  type RouteAccess,
} from './nativeRoute.js';

/**
 * Every native route of the API, one element per route. docs/api-contract.md is the source of
 * truth for behaviour; this catalog states the same routes in a machine-readable form and
 * openapi-coverage.test.ts fails when it and the app (or the document) disagree. A route added
 * to app.ts is added here in the same change. MLflow-compatible routes (/api/mlflow/*) follow
 * the official MLflow REST API and are not listed.
 */

const health = z.strictObject({ status: z.literal('ok') });
const csvDownload: NonJsonContent = {
  contentType: 'text/csv; charset=utf-8',
  description: `UTF-8 BOM付きCSV（attachment）。最大行数を超えて切り詰めたかは${RUN_EXPORT_TRUNCATED_HEADER}ヘッダ`,
};
const redirect: NonJsonContent = {
  contentType: 'text/plain',
  description: 'Locationへリダイレクトする',
};
const artifactBytes: NonJsonContent = {
  contentType: 'application/octet-stream',
  description: 'Artifactの本体。Content-TypeはArtifactのmimeType',
};
const artifactUploadBody: NonJsonContent = {
  contentType: 'application/octet-stream',
  description: 'Artifactの本体（任意のMIME type）。Content-Typeがそのまま保存される',
};
// GET /projects/:p/tasks and GET /projects/:p/models read single optional query values.
const taskListQuery = z.object({ experimentId: uuidSchema.optional() });
const modelListQuery = z.object({ name: nameSchema.optional() });
// evaluationRoutes parses each value on its own; lists accept repetition or commas.
const evaluationComparisonQuery = z.object({
  baselineAlias: nameSchema.optional(),
  baselineVersionId: uuidSchema.optional(),
  referenceDatasetVersionIds: z.string().optional(),
  codeVersionId: uuidSchema.optional(),
  evaluationRuleId: uuidSchema.optional(),
  metrics: z.string().optional(),
});
const artifactUploadQuery = z.object({ path: z.string() });
const artifactRangeHeaders = z.object({
  Range: z.string().optional(),
  'If-Range': z.string().optional(),
  'If-None-Match': z.string().optional(),
});
const partHeaders = z.object({ [PART_SHA256_HEADER]: z.string().optional() });

const RUNS_WRITE = projectEditor('runs:write');
const REGISTRY_WRITE = projectEditor('registry:write');
const ARTIFACTS_WRITE = projectEditor('artifacts:write');
// Deleting is for Project admins (decisions.md); a token needs artifacts:write (or admin).
const ARTIFACTS_DELETE: RouteAccess = { kind: 'project', role: 'admin', scope: 'artifacts:write' };
const JOBS_WRITE = projectEditor('jobs:write');
const SERVICE_ACCOUNT_ADMIN = { ...PROJECT_ADMIN, sessionOnly: true };

export const NATIVE_ROUTES: readonly NativeRoute[] = [
  // system
  {
    method: 'get',
    path: '/health',
    tag: 'system',
    summary: 'Health check（DB接続を確認）',
    access: { kind: 'public' },
    responses: { 200: health },
    errors: routeError(503, 'database_unavailable'),
  },
  {
    method: 'get',
    path: '/api/health',
    tag: 'system',
    summary: 'Health check（DB接続を確認）',
    access: { kind: 'public' },
    responses: { 200: health },
    errors: routeError(503, 'database_unavailable'),
  },
  {
    method: 'get',
    path: '/api/openapi.json',
    tag: 'system',
    summary: '独自APIのOpenAPI 3.1文書',
    access: { kind: 'signedIn', scope: 'read' },
    responses: { 200: z.record(z.string(), z.unknown()) },
  },

  // auth
  {
    method: 'get',
    path: '/api/auth/config',
    tag: 'auth',
    summary: '認証方式とlogin方法',
    access: { kind: 'public' },
    responses: { 200: contract.authConfigSchema },
  },
  {
    method: 'get',
    path: '/api/auth/me',
    tag: 'auth',
    summary: 'login中のUser',
    access: { kind: 'signedIn', scope: 'read' },
    responses: { 200: contract.authMeSchema },
  },
  {
    method: 'post',
    path: '/api/auth/dev-login',
    tag: 'auth',
    summary: '開発用login（development modeだけ）',
    access: { kind: 'public' },
    body: developmentLoginSchema('admin@localhost'),
    responses: { 200: z.strictObject({ user: contract.userSchema }) },
    errors: routeError(403, 'invalid_origin'),
  },
  {
    method: 'post',
    path: '/api/auth/local-login',
    tag: 'auth',
    summary: 'ローカルアカウントでlogin',
    access: { kind: 'public' },
    body: localLoginSchema,
    responses: { 200: contract.authMeSchema },
    errors: [
      ...routeError(401, 'invalid_credentials'),
      ...routeError(403, 'invalid_origin'),
      ...routeError(404, 'local_login_disabled'),
      ...routeError(429, 'rate_limited'),
    ],
  },
  {
    method: 'post',
    path: '/api/auth/change-password',
    tag: 'auth',
    summary: '自分のpasswordを変更',
    access: { kind: 'session' },
    body: changePasswordSchema,
    responses: { 204: null },
    errors: [
      ...routeError(401, 'invalid_credentials'),
      ...routeError(403, 'local_account_required'),
      ...routeError(409, 'password_changed_concurrently'),
      ...routeError(422, 'weak_password'),
      ...routeError(429, 'rate_limited'),
    ],
  },
  {
    method: 'get',
    path: '/api/auth/login',
    tag: 'auth',
    summary: 'SSO（OIDC）loginを開始',
    access: { kind: 'public' },
    responses: { 302: redirect },
    errors: routeError(429, 'rate_limited'),
  },
  {
    method: 'get',
    path: '/api/auth/callback',
    tag: 'auth',
    summary: 'SSO（OIDC）のcallback',
    access: { kind: 'public' },
    responses: { 302: redirect },
    errors: routeError(401, 'oidc_authentication_failed'),
  },
  {
    method: 'post',
    path: '/api/auth/logout',
    tag: 'auth',
    summary: 'logout',
    access: { kind: 'public' },
    responses: { 204: null },
    errors: routeError(403, 'invalid_origin'),
  },
  {
    method: 'post',
    path: '/api/auth/oidc/backchannel-logout',
    tag: 'auth',
    summary: 'IdPからのback-channel logout',
    access: { kind: 'public' },
    body: {
      contentType: 'application/x-www-form-urlencoded',
      description: 'logout_token（OpenID Connect Back-Channel Logout 1.0）',
    },
    responses: { 200: null },
    errors: [
      ...routeError(400, 'invalid_logout_token', 'logout_token_replayed'),
      ...routeError(404, 'oidc_disabled'),
      ...routeError(503, 'oidc_unavailable'),
    ],
  },
  {
    method: 'get',
    path: '/api/auth/token',
    tag: 'auth',
    summary: '認証に使ったAPI token自身のscope',
    access: { kind: 'signedIn', scope: 'read' },
    responses: { 200: contract.currentApiTokenSchema },
    errors: routeError(400, 'api_token_required'),
  },
  {
    method: 'get',
    path: '/api/auth/groups',
    tag: 'access',
    summary: '既知のSSO group名',
    access: { kind: 'signedIn', scope: 'admin' },
    responses: { 200: contract.itemsOf(z.string()) },
  },
  {
    method: 'get',
    path: '/api/users',
    tag: 'access',
    summary: 'Userの検索（Project管理者向け）',
    access: { kind: 'signedIn', scope: 'admin' },
    query: userSearchQuerySchema,
    responses: { 200: contract.itemsOf(contract.userSearchResultSchema) },
  },
  {
    method: 'get',
    path: '/api/account',
    tag: 'auth',
    summary: '自分のアカウント',
    access: { kind: 'signedIn', scope: 'read' },
    responses: { 200: contract.accountSchema },
  },

  // audit
  {
    method: 'get',
    path: '/api/audit-events',
    tag: 'audit',
    summary: '監査ログ（全体）',
    access: { kind: 'globalAdmin', sessionOnly: true },
    query: auditEventQuerySchema,
    responses: { 200: contract.auditEventPageSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/audit-events',
    tag: 'audit',
    summary: '監査ログ（Project）',
    access: PROJECT_ADMIN,
    query: projectAuditEventQuerySchema,
    responses: { 200: contract.auditEventPageSchema },
  },

  // projects and access
  {
    method: 'get',
    path: '/api/projects',
    tag: 'projects',
    summary: '参加しているProject',
    access: { kind: 'signedIn', scope: 'read' },
    responses: { 200: contract.itemsOf(contract.projectSchema) },
  },
  {
    method: 'post',
    path: '/api/projects',
    tag: 'projects',
    summary: 'Projectを作成',
    access: { kind: 'signedIn', scope: 'admin' },
    body: projectCreateSchema,
    responses: { 201: contract.projectSchema },
    errors: routeError(422, 'backend_unavailable'),
  },
  {
    method: 'patch',
    path: '/api/projects/:p',
    tag: 'projects',
    summary: 'Projectを変更',
    access: PROJECT_ADMIN,
    body: projectPatchSchema,
    responses: { 200: contract.projectSchema },
    errors: routeError(422, 'backend_unavailable'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/members',
    tag: 'access',
    summary: 'Projectのメンバー',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.projectMemberSchema) },
  },
  {
    method: 'put',
    path: '/api/projects/:p/members/:userId',
    tag: 'access',
    summary: 'メンバーのroleを設定',
    access: PROJECT_ADMIN,
    body: roleAssignmentSchema,
    responses: { 200: contract.projectMemberSchema },
    errors: routeError(409, 'conflict'),
  },
  {
    method: 'delete',
    path: '/api/projects/:p/members/:userId',
    tag: 'access',
    summary: 'メンバーを外す',
    access: PROJECT_ADMIN,
    responses: { 204: null },
    errors: routeError(409, 'conflict'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/group-bindings',
    tag: 'access',
    summary: 'SSO groupのbinding',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.projectGroupBindingSchema) },
  },
  {
    method: 'put',
    path: '/api/projects/:p/group-bindings/:group',
    tag: 'access',
    summary: 'groupのroleを設定',
    access: PROJECT_ADMIN,
    body: roleAssignmentSchema,
    responses: { 200: contract.projectGroupBindingSchema },
    errors: routeError(409, 'conflict'),
  },
  {
    method: 'delete',
    path: '/api/projects/:p/group-bindings/:group',
    tag: 'access',
    summary: 'groupのbindingを外す',
    access: PROJECT_ADMIN,
    responses: { 204: null },
    errors: routeError(409, 'conflict'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/tokens',
    tag: 'tokens',
    summary: 'Projectに限定されたtoken',
    access: PROJECT_ADMIN,
    responses: { 200: contract.itemsOf(contract.tokenSummarySchema) },
  },
  {
    method: 'get',
    path: '/api/projects/:p/experiments',
    tag: 'projects',
    summary: 'Experiment一覧',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.experimentSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/experiments',
    tag: 'projects',
    summary: 'Experimentを作成',
    access: RUNS_WRITE,
    body: namedEntitySchema,
    responses: { 201: contract.experimentSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/service-accounts',
    tag: 'tokens',
    summary: 'Service Account一覧',
    access: SERVICE_ACCOUNT_ADMIN,
    responses: { 200: contract.itemsOf(contract.serviceAccountSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/service-accounts',
    tag: 'tokens',
    summary: 'Service Accountを作成',
    access: SERVICE_ACCOUNT_ADMIN,
    body: serviceAccountCreateSchema,
    responses: { 201: contract.serviceAccountSchema },
  },
  {
    method: 'patch',
    path: '/api/projects/:p/service-accounts/:id',
    tag: 'tokens',
    summary: 'Service Accountを変更・無効化',
    access: SERVICE_ACCOUNT_ADMIN,
    body: serviceAccountUpdateSchema,
    responses: { 200: contract.serviceAccountSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/service-accounts/:id/tokens',
    tag: 'tokens',
    summary: 'Service Accountのtokenを発行',
    access: SERVICE_ACCOUNT_ADMIN,
    body: serviceAccountTokenCreateSchema,
    responses: { 201: contract.issuedTokenSchema },
    errors: [
      ...routeError(409, 'service_account_disabled', 'service_account_role_missing'),
      ...routeError(422, 'scope_exceeds_role', 'token_lifetime_exceeded', 'invalid_expiry'),
    ],
  },
  {
    method: 'get',
    path: '/api/tokens',
    tag: 'tokens',
    summary: '自分のtoken',
    access: { kind: 'signedIn', scope: 'read' },
    responses: { 200: contract.itemsOf(contract.tokenSummarySchema) },
  },
  {
    method: 'post',
    path: '/api/tokens',
    tag: 'tokens',
    summary: 'API tokenを発行',
    access: { kind: 'session' },
    body: tokenCreateSchema,
    responses: { 201: contract.issuedTokenSchema },
    errors: routeError(422, 'token_lifetime_exceeded', 'invalid_expiry'),
  },
  {
    method: 'delete',
    path: '/api/tokens/:id',
    tag: 'tokens',
    summary: 'API tokenを失効',
    access: { kind: 'session' },
    responses: { 204: null },
    errors: routeError(403, 'token_forbidden'),
  },

  // registry
  {
    method: 'get',
    path: '/api/projects/:p/models',
    tag: 'registry',
    summary: 'Model一覧',
    access: PROJECT_VIEWER,
    query: modelListQuery,
    responses: { 200: contract.itemsOf(contract.modelSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/models',
    tag: 'registry',
    summary: 'Modelを作成',
    access: REGISTRY_WRITE,
    body: modelCreateSchema,
    responses: { 201: contract.modelSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/models/:id/versions',
    tag: 'registry',
    summary: 'ModelVersion一覧',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.modelVersionSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/models/:id/versions',
    tag: 'registry',
    summary: 'ModelVersionを登録（版は不変）',
    access: REGISTRY_WRITE,
    body: modelVersionCreateSchema,
    responses: { 201: contract.modelVersionSchema },
    errors: routeError(422, 'output_model_kind', 'source_run_deleted'),
  },
  {
    method: 'put',
    path: '/api/projects/:p/models/:id/aliases/:alias',
    tag: 'registry',
    summary: 'aliasを設定',
    access: REGISTRY_WRITE,
    body: modelAliasAssignmentSchema,
    responses: { 200: contract.modelSchema },
    errors: [
      ...routeError(403, 'alias_protected'),
      ...routeError(409, 'alias_evaluation_not_passed'),
      ...routeError(
        422,
        'alias_evaluation_required',
        'alias_reason_required',
        'alias_evaluation_mismatch',
      ),
    ],
  },
  {
    method: 'delete',
    path: '/api/projects/:p/models/:id/aliases/:alias',
    tag: 'registry',
    summary: 'aliasを外す',
    access: REGISTRY_WRITE,
    body: modelAliasRemovalSchema,
    bodyOptional: true,
    responses: { 204: null },
    errors: routeError(403, 'alias_protected'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/models/:id/alias-events',
    tag: 'registry',
    summary: 'aliasの変更履歴',
    access: PROJECT_VIEWER,
    query: modelAliasEventQuerySchema,
    responses: { 200: contract.modelAliasEventPageSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/alias-protections',
    tag: 'registry',
    summary: '保護aliasの一覧',
    access: PROJECT_VIEWER,
    query: modelAliasProtectionQuerySchema,
    responses: { 200: contract.itemsOf(contract.modelAliasProtectionSchema) },
  },
  {
    method: 'put',
    path: '/api/projects/:p/alias-protections/:alias',
    tag: 'registry',
    summary: 'aliasを保護する（設定の置き換え）',
    access: PROJECT_ADMIN,
    query: modelAliasProtectionQuerySchema,
    body: modelAliasProtectionInputSchema,
    responses: { 200: contract.modelAliasProtectionSchema },
  },
  {
    method: 'delete',
    path: '/api/projects/:p/alias-protections/:alias',
    tag: 'registry',
    summary: 'aliasの保護を外す',
    access: PROJECT_ADMIN,
    query: modelAliasProtectionQuerySchema,
    responses: { 204: null },
  },
  {
    method: 'get',
    path: '/api/projects/:p/model-versions/:id',
    tag: 'registry',
    summary: 'ModelVersionの詳細',
    access: PROJECT_VIEWER,
    responses: { 200: contract.modelVersionDetailSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/model-versions/:id/evaluations',
    tag: 'evaluation',
    summary: 'ModelVersionの評価の集約',
    access: PROJECT_VIEWER,
    query: modelVersionEvaluationQuerySchema,
    responses: { 200: contract.modelVersionEvaluationSummarySchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/models/:id/versions/:v/evaluation-comparison',
    tag: 'evaluation',
    summary: '基準版との評価比較',
    access: PROJECT_VIEWER,
    query: evaluationComparisonQuery,
    responses: { 200: contract.evaluationComparisonSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/codes',
    tag: 'registry',
    summary: 'Code一覧',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.codeSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/codes',
    tag: 'registry',
    summary: 'Codeを作成',
    access: REGISTRY_WRITE,
    body: namedEntitySchema,
    responses: { 201: contract.codeSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/codes/:id/versions',
    tag: 'registry',
    summary: 'CodeVersion一覧',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.codeVersionSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/codes/:id/versions',
    tag: 'registry',
    summary: 'CodeVersionを登録',
    access: REGISTRY_WRITE,
    body: codeVersionCreateSchema,
    responses: { 201: contract.codeVersionSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/repository-files',
    tag: 'registry',
    summary: 'Git commitのファイルを読む',
    access: REGISTRY_WRITE,
    body: repositoryFilesSchema,
    responses: { 200: contract.repositoryFilesSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/datasets',
    tag: 'registry',
    summary: 'Dataset一覧',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.datasetSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/datasets',
    tag: 'registry',
    summary: 'Datasetを作成',
    access: REGISTRY_WRITE,
    body: datasetCreateSchema,
    responses: { 201: contract.datasetSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/datasets/:id/versions',
    tag: 'registry',
    summary: 'DatasetVersion一覧',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.datasetVersionSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/datasets/:id/versions',
    tag: 'registry',
    summary: 'DatasetVersionを登録（参照またはArtifactを本体にする）',
    access: REGISTRY_WRITE,
    body: datasetVersionRequestSchema,
    maxBodyBytes: MAX_DATASET_VERSION_BODY_BYTES,
    responses: { 201: contract.datasetVersionSchema },
    errors: [
      ...routeError(409, 'already_exists'),
      ...routeError(
        422,
        'dataset_digest_mismatch',
        'dataset_artifact_not_found',
        'dataset_content_empty',
        'dataset_too_many_files',
        'dataset_source_run_mismatch',
      ),
    ],
  },
  {
    method: 'get',
    path: '/api/projects/:p/datasets/:id/versions/:v/files',
    tag: 'registry',
    summary: 'DatasetVersionのファイル',
    access: PROJECT_VIEWER,
    query: datasetFileListQuerySchema,
    responses: { 200: contract.datasetVersionFilePageSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/datasets/:id/versions/:v/files/tree',
    tag: 'registry',
    summary: 'DatasetVersionのディレクトリ1階層',
    access: PROJECT_VIEWER,
    query: datasetFileTreeQuerySchema,
    responses: { 200: contract.artifactTreeSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifacts/by-digest',
    tag: 'artifacts',
    summary: 'sha256とsizeが一致する保存済みArtifact',
    access: PROJECT_VIEWER,
    query: artifactDigestQuerySchema,
    responses: { 200: contract.artifactSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/lineage',
    tag: 'registry',
    summary: 'Projectのlineage',
    access: PROJECT_VIEWER,
    responses: { 200: contract.lineageGraphSchema },
  },

  // automation
  {
    method: 'get',
    path: '/api/projects/:p/automation-rules',
    tag: 'automation',
    summary: '自動実行rule一覧',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.modelAutomationRuleSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/automation-rules',
    tag: 'automation',
    summary: '自動実行ruleを作成（不変）',
    access: PROJECT_ADMIN,
    body: automationRuleCreateSchema,
    responses: { 201: contract.modelAutomationRuleSchema },
    errors: routeError(
      422,
      'invalid_automation_trigger',
      'upstream_rule_disabled',
      'automation_chain_too_deep',
      'automation_chain_cycle',
    ),
  },
  {
    method: 'patch',
    path: '/api/projects/:p/automation-rules/:id',
    tag: 'automation',
    summary: 'ruleの有効・無効',
    access: PROJECT_ADMIN,
    body: modelAutomationToggleSchema,
    responses: { 200: contract.modelAutomationRuleSchema },
  },
  {
    method: 'put',
    path: '/api/projects/:p/automation-rules/:id/owner',
    tag: 'automation',
    summary: 'ruleの所有者をService Accountへ移す',
    access: PROJECT_ADMIN,
    body: automationRuleOwnerSchema,
    responses: { 200: contract.modelAutomationRuleSchema },
    errors: routeError(422, 'invalid_automation_owner'),
  },
  {
    method: 'post',
    path: '/api/projects/:p/automation-rules/:id/executions',
    tag: 'automation',
    summary: 'ruleを既存の版・上流Runへ手動適用',
    access: PROJECT_ADMIN,
    body: automationExecutionCreateSchema,
    responses: { 201: contract.modelAutomationExecutionSchema },
    errors: [
      ...routeError(409, 'automation_execution_active'),
      ...routeError(
        422,
        'automation_trigger_mismatch',
        'upstream_run_not_finished',
        'upstream_rule_mismatch',
        'upstream_outputs_missing',
        'automation_rule_disabled',
        'incompatible_model_family',
      ),
    ],
  },
  {
    method: 'get',
    path: '/api/projects/:p/automation-executions',
    tag: 'automation',
    summary: '自動実行の履歴',
    access: PROJECT_VIEWER,
    query: automationExecutionQuerySchema,
    responses: { 200: contract.modelAutomationExecutionPageSchema },
  },

  // runs
  {
    method: 'post',
    path: '/api/projects/:p/runs/compare',
    tag: 'runs',
    summary: 'Runの比較表',
    access: PROJECT_VIEWER,
    body: runComparisonRequestSchema,
    responses: { 200: contract.runComparisonSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/compare.csv',
    tag: 'runs',
    summary: 'Runの比較表をCSVで出力',
    access: PROJECT_VIEWER,
    query: runComparisonCsvQuerySchema,
    responses: { 200: csvDownload },
  },
  {
    method: 'post',
    path: '/api/projects/:p/runs/search/export.csv',
    tag: 'runs',
    summary: '検索に一致したRunをCSVで出力',
    access: PROJECT_VIEWER,
    body: runSearchSchema,
    responses: { 200: csvDownload },
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs',
    tag: 'runs',
    summary: 'Run一覧（互換。検索はruns/search）',
    access: PROJECT_VIEWER,
    query: runQuerySchema,
    responses: { 200: contract.itemsOf(contract.runSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/runs',
    tag: 'runs',
    summary: 'Runを作成',
    access: RUNS_WRITE,
    body: runCreateSchema,
    responses: { 201: contract.runSchema },
    errors: routeError(
      422,
      'reserved_tag',
      'checkpoint_not_found',
      'checkpoint_kind_mismatch',
      'checkpoint_code_mismatch',
      'checkpoint_artifact_missing',
    ),
  },
  {
    method: 'post',
    path: '/api/projects/:p/runs/search',
    tag: 'runs',
    summary: 'Runの検索（MLflowと同じfilter構文）',
    access: PROJECT_VIEWER,
    body: runSearchSchema,
    responses: { 200: contract.runSearchPageSchema },
    errors: routeError(400, 'invalid_parameter_value', 'invalid_cursor'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r',
    tag: 'runs',
    summary: 'Runの詳細',
    access: PROJECT_VIEWER,
    responses: { 200: contract.runSchema },
  },
  {
    method: 'patch',
    path: '/api/projects/:p/runs/:r',
    tag: 'runs',
    summary: 'Runの状態・tagsを変更',
    access: RUNS_WRITE,
    body: runPatchSchema,
    responses: { 200: contract.runSchema },
    errors: [...routeError(409, 'run_finalized'), ...routeError(422, 'reserved_tag')],
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/metrics',
    tag: 'runs',
    summary: 'Runのmetrics',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.metricPointSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/runs/:r/metrics',
    tag: 'runs',
    summary: 'metricsを記録',
    access: RUNS_WRITE,
    body: metricBatchSchema,
    responses: { 204: null },
    errors: routeError(409, 'run_finalized'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/logs',
    tag: 'runs',
    summary: 'Runのlog',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.logEntrySchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/runs/:r/logs',
    tag: 'runs',
    summary: 'logを記録',
    access: RUNS_WRITE,
    body: logBatchSchema,
    responses: { 204: null },
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/output-registration',
    tag: 'runs',
    summary: 'Task側の出力モデル登録の結果',
    access: PROJECT_VIEWER,
    responses: { 200: contract.runOutputRegistrationSchema },
    errors: routeError(404, 'output_registration_not_found'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/downstream',
    tag: 'runs',
    summary: 'Runの出力から起動した下流Run',
    access: PROJECT_VIEWER,
    query: runDownstreamQuerySchema,
    responses: { 200: contract.runDownstreamPageSchema },
  },
  {
    method: 'put',
    path: '/api/projects/:p/runs/:r/note',
    tag: 'collaboration',
    summary: 'Runの説明文（Markdown）',
    access: RUNS_WRITE,
    body: runNoteUpdateSchema,
    responses: { 200: contract.runNoteSchema },
    errors: routeError(409, 'run_deleted'),
  },

  // media
  {
    method: 'post',
    path: '/api/projects/:p/runs/:r/media',
    tag: 'media',
    summary: 'stepごとのmediaを登録（クライアントのidで冪等）',
    access: RUNS_WRITE,
    body: runMediaCreateSchema,
    responses: { 201: contract.runMediaListSchema },
    errors: [
      ...routeError(409, 'media_conflict', 'media_exists', 'run_finalized'),
      ...routeError(413, 'media_table_too_large'),
      ...routeError(
        422,
        'media_duplicate_item',
        'media_artifact_unavailable',
        'media_artifact_run',
        'media_kind_mismatch',
        'media_table_invalid',
        'unsupported_table_format',
      ),
    ],
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/media',
    tag: 'media',
    summary: 'Runのmedia（step順）',
    access: PROJECT_VIEWER,
    query: runMediaListQuerySchema,
    responses: { 200: contract.runMediaPageSchema },
    errors: routeError(400, 'invalid_cursor'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/media/keys',
    tag: 'media',
    summary: 'Runのmediaのkeyごとの件数とstepの範囲',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.runMediaKeySummarySchema) },
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/media/:mediaId/table',
    tag: 'media',
    summary: '表のmediaを行の範囲で読む',
    access: PROJECT_VIEWER,
    query: mediaTableQuerySchema,
    responses: { 200: contract.mediaTablePageSchema },
    errors: [
      ...routeError(413, 'media_table_too_large'),
      ...routeError(422, 'media_not_table', 'unsupported_table_format'),
    ],
  },
  {
    method: 'post',
    path: '/api/projects/:p/media/compare',
    tag: 'media',
    summary: '複数Runの同じkeyのmediaをstepで並べる',
    access: PROJECT_VIEWER,
    body: mediaCompareSchema,
    responses: { 200: contract.mediaCompareGridSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/runs/:r/resume',
    tag: 'runs',
    summary: '終端のRunを再開',
    access: RUNS_WRITE,
    body: runResumeRequestSchema,
    responses: { 200: contract.runResumeResultSchema },
    errors: routeError(409, 'run_finalized', 'run_not_started', 'run_deleted'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/resume-events',
    tag: 'runs',
    summary: 'Runの再開履歴',
    access: PROJECT_VIEWER,
    responses: { 200: contract.runResumeEventPageSchema },
  },

  // analysis
  {
    method: 'post',
    path: '/api/projects/:p/metrics/series',
    tag: 'analysis',
    summary: 'メトリクス系列（間引き）',
    access: PROJECT_VIEWER,
    body: metricSeriesRequestSchema,
    responses: { 200: contract.metricSeriesResponseSchema },
    errors: routeError(503, 'series_query_timeout'),
  },
  {
    method: 'post',
    path: '/api/projects/:p/metrics/groups',
    tag: 'analysis',
    summary: 'Runグループのメトリクス系列',
    access: PROJECT_VIEWER,
    body: metricGroupsRequestSchema,
    responses: { 200: contract.metricGroupsResponseSchema },
    errors: [
      ...routeError(422, 'too_many_runs', 'too_many_groups', 'too_many_points'),
      ...routeError(503, 'series_query_timeout'),
    ],
  },
  {
    method: 'post',
    path: '/api/projects/:p/runs/analysis/table',
    tag: 'analysis',
    summary: 'params×metricsの表',
    access: PROJECT_VIEWER,
    body: runAnalysisTableRequestSchema,
    responses: { 200: contract.runAnalysisTableResponseSchema },
    errors: routeError(422, 'too_many_runs'),
  },
  {
    method: 'post',
    path: '/api/projects/:p/runs/analysis/parameter-importance',
    tag: 'analysis',
    summary: 'パラメータ重要度',
    access: PROJECT_VIEWER,
    body: parameterImportanceRequestSchema,
    responses: { 200: contract.parameterImportanceResultSchema },
    errors: routeError(422, 'target_metric_required', 'too_many_runs'),
  },

  // tasks
  {
    method: 'get',
    path: '/api/projects/:p/tasks',
    tag: 'tasks',
    summary: 'Task一覧',
    access: PROJECT_VIEWER,
    query: taskListQuery,
    responses: { 200: contract.itemsOf(contract.experimentTaskSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/tasks',
    tag: 'tasks',
    summary: 'Taskを作成',
    access: REGISTRY_WRITE,
    body: taskCreateSchema,
    responses: { 201: contract.experimentTaskSchema },
    errors: routeError(
      422,
      'output_model_kind',
      'incompatible_model_family',
      'model_family_mismatch',
      'reserved_tag',
    ),
  },
  {
    method: 'get',
    path: '/api/projects/:p/tasks/:id',
    tag: 'tasks',
    summary: 'Taskの詳細',
    access: PROJECT_VIEWER,
    responses: { 200: contract.experimentTaskSchema },
  },
  {
    method: 'patch',
    path: '/api/projects/:p/tasks/:id',
    tag: 'tasks',
    summary: 'Taskを改訂（revisionが増える）',
    access: REGISTRY_WRITE,
    body: taskPatchSchema,
    responses: { 200: contract.experimentTaskSchema },
    errors: routeError(
      422,
      'output_model_kind',
      'incompatible_model_family',
      'model_family_mismatch',
      'reserved_tag',
    ),
  },
  {
    method: 'post',
    path: '/api/projects/:p/tasks/:id/launch',
    tag: 'tasks',
    summary: 'Taskを実行（Run/Jobを作る）。tokenにはjobs:writeも要る',
    access: RUNS_WRITE,
    body: taskLaunchSchema,
    responses: { 201: contract.taskExecutionSchema },
    errors: routeError(
      422,
      'checkpoint_not_found',
      'checkpoint_kind_mismatch',
      'checkpoint_code_mismatch',
      'checkpoint_artifact_missing',
    ),
  },
  {
    method: 'get',
    path: '/api/projects/:p/tasks/:id/runs',
    tag: 'tasks',
    summary: 'TaskのRun履歴',
    access: PROJECT_VIEWER,
    query: taskHistoryQuerySchema,
    responses: { 200: contract.taskRunPageSchema },
  },

  // artifacts
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/artifacts',
    tag: 'artifacts',
    summary: 'RunのArtifact一覧',
    access: PROJECT_VIEWER,
    query: runArtifactQuerySchema,
    responses: { 200: contract.artifactPageSchema },
    errors: routeError(400, 'invalid_cursor'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/artifacts/tree',
    tag: 'artifacts',
    summary: 'RunのArtifactのディレクトリ1階層',
    access: PROJECT_VIEWER,
    query: artifactTreeQuerySchema,
    responses: { 200: contract.artifactTreeSchema },
  },
  {
    method: 'put',
    path: '/api/projects/:p/runs/:r/artifacts',
    tag: 'artifacts',
    summary: 'RunのArtifactを1回で保存',
    access: ARTIFACTS_WRITE,
    query: artifactUploadQuery,
    body: artifactUploadBody,
    responses: { 201: contract.artifactSchema },
    errors: [
      ...routeError(409, 'storage_backend_disabled'),
      ...routeError(413, 'artifact_too_large'),
    ],
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifacts',
    tag: 'artifacts',
    summary: 'ProjectのArtifact一覧',
    access: PROJECT_VIEWER,
    query: artifactCatalogQuerySchema,
    responses: { 200: contract.artifactPageSchema },
    errors: routeError(400, 'invalid_cursor'),
  },
  {
    method: 'put',
    path: '/api/projects/:p/artifacts',
    tag: 'artifacts',
    summary: 'Runに属さないArtifactを1回で保存',
    access: ARTIFACTS_WRITE,
    query: artifactUploadQuery,
    body: artifactUploadBody,
    responses: { 201: contract.artifactSchema },
    errors: [
      ...routeError(409, 'storage_backend_disabled'),
      ...routeError(413, 'artifact_too_large'),
    ],
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifacts/:a',
    tag: 'artifacts',
    summary: 'Artifactのmetadata',
    access: PROJECT_VIEWER,
    responses: { 200: contract.artifactSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifacts/:a/content',
    tag: 'artifacts',
    summary: 'Artifactの本体（Range・ETag対応）',
    access: PROJECT_VIEWER,
    headers: artifactRangeHeaders,
    responses: { 200: artifactBytes, 206: artifactBytes, 304: null },
    errors: [...routeError(416, 'invalid_range'), ...routeError(503, 'artifact_read_failed')],
  },
  {
    method: 'delete',
    path: '/api/projects/:p/artifacts/:a',
    tag: 'artifacts',
    summary: 'Artifactを削除（猶予期間の後にblobを回収）',
    access: ARTIFACTS_DELETE,
    responses: { 200: contract.artifactSchema },
    errors: routeError(409, 'artifact_in_use'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifact-usage',
    tag: 'artifacts',
    summary: '保存先ごとのArtifact使用量',
    access: PROJECT_VIEWER,
    responses: { 200: contract.artifactUsageSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifacts/:a/media-info',
    tag: 'artifacts',
    summary: '音声・動画のmedia情報',
    access: PROJECT_VIEWER,
    responses: { 200: contract.artifactMediaInfoSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifact-media-info',
    tag: 'artifacts',
    summary: '複数Artifactのmedia情報',
    access: PROJECT_VIEWER,
    query: artifactMediaInfoQuerySchema,
    responses: { 200: contract.itemsOf(contract.artifactMediaInfoSchema) },
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifacts/:a/previews',
    tag: 'artifacts',
    summary: 'サーバー側preview',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.artifactPreviewSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/artifact-uploads',
    tag: 'artifact-uploads',
    summary: '再開可能なupload sessionを作成',
    access: ARTIFACTS_WRITE,
    body: uploadCreateSchema,
    responses: { 201: contract.artifactUploadSchema },
    errors: [
      ...routeError(409, 'run_deleted', 'storage_backend_disabled'),
      ...routeError(413, 'artifact_too_large'),
      ...routeError(422, 'invalid_part_size', 'too_many_parts'),
    ],
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifact-uploads',
    tag: 'artifact-uploads',
    summary: '自分のupload session',
    access: ARTIFACTS_WRITE,
    query: uploadListQuerySchema,
    responses: { 200: contract.itemsOf(contract.artifactUploadSchema) },
  },
  {
    method: 'get',
    path: '/api/projects/:p/artifact-uploads/:u',
    tag: 'artifact-uploads',
    summary: 'upload sessionと受信済みpart',
    access: ARTIFACTS_WRITE,
    responses: { 200: contract.artifactUploadDetailSchema },
    errors: routeError(403, 'upload_forbidden'),
  },
  {
    method: 'put',
    path: '/api/projects/:p/artifact-uploads/:u/parts/:n',
    tag: 'artifact-uploads',
    summary: 'partを送る（同じ番号の再送は置き換え）',
    access: ARTIFACTS_WRITE,
    headers: partHeaders,
    body: {
      contentType: 'application/octet-stream',
      description: 'partの本体（最後以外はpartSizeちょうど）',
    },
    responses: { 200: contract.artifactUploadPartSchema },
    errors: [
      ...routeError(403, 'upload_forbidden'),
      ...routeError(409, 'upload_not_open', 'upload_expired'),
      ...routeError(422, 'part_size_mismatch', 'part_checksum_mismatch'),
    ],
  },
  {
    method: 'post',
    path: '/api/projects/:p/artifact-uploads/:u/complete',
    tag: 'artifact-uploads',
    summary: 'partを結合して検証する（非同期）',
    access: ARTIFACTS_WRITE,
    responses: { 202: contract.artifactUploadSchema },
    errors: [
      ...routeError(403, 'upload_forbidden'),
      ...routeError(409, 'upload_incomplete', 'run_deleted'),
    ],
  },
  {
    method: 'delete',
    path: '/api/projects/:p/artifact-uploads/:u',
    tag: 'artifact-uploads',
    summary: 'upload sessionを中止',
    access: ARTIFACTS_WRITE,
    responses: { 200: contract.artifactUploadSchema },
    errors: [...routeError(403, 'upload_forbidden'), ...routeError(409, 'upload_not_open')],
  },
  {
    method: 'get',
    path: '/api/storage/backends',
    tag: 'artifacts',
    summary: '新しいArtifactを保存できる保存先',
    access: { kind: 'signedIn', scope: 'read' },
    responses: { 200: contract.storageBackendChoicesSchema },
  },

  // execution
  {
    method: 'get',
    path: '/api/projects/:p/jobs',
    tag: 'execution',
    summary: 'Job一覧',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.jobSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/jobs',
    tag: 'execution',
    summary: 'Jobを作成',
    access: JOBS_WRITE,
    body: jobCreateSchema,
    responses: { 201: contract.jobSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/jobs/:j/cancel',
    tag: 'execution',
    summary: 'Jobを取り消す',
    access: JOBS_WRITE,
    responses: { 200: contract.jobSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/jobs/:j/retry',
    tag: 'execution',
    summary: 'Jobを再実行（checkpointから再開も可）',
    access: JOBS_WRITE,
    body: jobRetryRequestSchema,
    bodyOptional: true,
    responses: { 201: contract.taskExecutionSchema },
    errors: [
      ...routeError(409, 'job_already_retried'),
      ...routeError(
        422,
        'checkpoint_not_found',
        'checkpoint_kind_mismatch',
        'checkpoint_code_mismatch',
        'checkpoint_artifact_missing',
      ),
    ],
  },
  {
    method: 'get',
    path: '/api/targets',
    tag: 'execution',
    summary: '計算機（ComputeTarget）一覧',
    access: { kind: 'signedIn', scope: 'read' },
    responses: { 200: contract.itemsOf(contract.computeTargetSchema) },
  },
  {
    method: 'post',
    path: '/api/targets',
    tag: 'execution',
    summary: '計算機を登録',
    access: GLOBAL_ADMIN,
    body: targetSchema,
    responses: { 201: contract.computeTargetSchema },
  },
  {
    method: 'patch',
    path: '/api/targets/:id',
    tag: 'execution',
    summary: '計算機を変更',
    access: GLOBAL_ADMIN,
    body: targetPatchSchema,
    responses: { 200: contract.computeTargetSchema },
  },
  {
    method: 'post',
    path: '/api/targets/:id/checks',
    tag: 'execution',
    summary: '計算機の接続確認を依頼',
    access: GLOBAL_ADMIN,
    responses: { 201: contract.targetCheckSchema },
    errors: routeError(409, 'target_check_in_progress'),
  },
  {
    method: 'get',
    path: '/api/targets/:id/checks',
    tag: 'execution',
    summary: '接続確認の履歴',
    access: GLOBAL_ADMIN,
    responses: { 200: contract.itemsOf(contract.targetCheckSchema) },
  },
  {
    method: 'get',
    path: '/api/projects/:p/workers',
    tag: 'execution',
    summary: 'Projectのworker',
    access: PROJECT_VIEWER,
    responses: { 200: contract.itemsOf(contract.workerPresenceSchema) },
  },
  {
    method: 'get',
    path: '/api/workers',
    tag: 'execution',
    summary: '全worker',
    access: GLOBAL_ADMIN,
    responses: { 200: contract.itemsOf(contract.workerPresenceSchema) },
  },

  // worker protocol
  {
    method: 'post',
    path: '/api/worker/claim',
    tag: 'worker',
    summary: 'Jobを1件受け取る',
    access: WORKER,
    body: workerClaimSchema,
    responses: { 200: z.strictObject({ item: contract.workerJobSchema.nullable() }) },
  },
  {
    method: 'post',
    path: '/api/worker/resume',
    tag: 'worker',
    summary: '再起動したworkerが実行中のJobを取り戻す',
    access: WORKER,
    body: workerResumeSchema,
    responses: { 200: contract.itemsOf(contract.workerJobSchema) },
  },
  {
    method: 'post',
    path: '/api/worker/jobs/:id/heartbeat',
    tag: 'worker',
    summary: 'heartbeat（取り消し要求を返す）',
    access: WORKER,
    body: heartbeatSchema,
    responses: { 200: z.strictObject({ cancelRequested: z.boolean() }) },
    errors: routeError(409, 'invalid_lease'),
  },
  {
    method: 'post',
    path: '/api/worker/jobs/:id/metrics',
    tag: 'worker',
    summary: 'Jobのmetrics',
    access: WORKER,
    body: workerMetricSchema,
    responses: { 204: null },
    errors: routeError(409, 'invalid_lease'),
  },
  {
    method: 'post',
    path: '/api/worker/jobs/:id/logs',
    tag: 'worker',
    summary: 'Jobのlog',
    access: WORKER,
    body: workerLogSchema,
    responses: { 204: null },
    errors: routeError(409, 'invalid_lease'),
  },
  {
    method: 'post',
    path: '/api/worker/jobs/:id/outputs',
    tag: 'worker',
    summary: '出力の宣言（result.json version 2）。tokenにはregistry:writeも要る',
    access: WORKER,
    body: workerOutputsSchema,
    responses: { 200: contract.workerOutputsResponseSchema },
    errors: [
      ...routeError(409, 'invalid_lease', 'output_declaration_mismatch', 'conflict'),
      ...routeError(
        422,
        'output_artifact_not_found',
        'output_declaration_limit',
        'output_model_kind',
        'output_model_conflict',
        'output_model_required',
        'model_deleted',
      ),
    ],
  },
  {
    method: 'post',
    path: '/api/worker/jobs/:id/complete',
    tag: 'worker',
    summary: 'Jobの終了を報告',
    access: WORKER,
    body: completeSchema,
    responses: { 200: contract.jobSchema },
    errors: routeError(409, 'invalid_lease'),
  },
  {
    method: 'post',
    path: '/api/worker/target-checks/claim',
    tag: 'worker',
    summary: '接続確認を1件受け取る',
    access: WORKER,
    body: targetCheckClaimSchema,
    responses: { 200: z.strictObject({ item: contract.workerTargetCheckSchema.nullable() }) },
  },
  {
    method: 'post',
    path: '/api/worker/target-checks/:id/complete',
    tag: 'worker',
    summary: '接続確認の結果を報告',
    access: WORKER,
    body: targetCheckCompleteSchema,
    responses: { 200: contract.targetCheckSchema },
    errors: [
      ...routeError(409, 'invalid_lease', 'target_check_finished'),
      ...routeError(422, 'target_check_result_too_large', 'target_check_secret_in_result'),
    ],
  },

  // plugins
  {
    method: 'get',
    path: '/api/projects/:p/plugins',
    tag: 'plugins',
    summary: 'Mado plugin接続',
    access: PROJECT_ADMIN,
    responses: { 200: contract.itemsOf(contract.pluginConnectionSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/plugins',
    tag: 'plugins',
    summary: 'plugin接続を登録（全体管理者）',
    access: GLOBAL_ADMIN,
    body: pluginCreateSchema,
    responses: { 201: contract.pluginConnectionSchema },
  },
  {
    method: 'patch',
    path: '/api/projects/:p/plugins/:id',
    tag: 'plugins',
    summary: 'plugin接続を変更（全体管理者）',
    access: GLOBAL_ADMIN,
    body: pluginPatchSchema,
    responses: { 200: contract.pluginConnectionSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/plugins/:id/check',
    tag: 'plugins',
    summary: 'pluginのmanifestを確認',
    access: PROJECT_ADMIN,
    responses: { 200: contract.pluginManifestSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:p/plugins/:id/metrics',
    tag: 'plugins',
    summary: 'pluginのPrometheus metrics',
    access: PROJECT_ADMIN,
    responses: { 200: z.strictObject({ prometheus: z.string() }) },
  },
  {
    method: 'get',
    path: '/api/projects/:p/plugins/:id/outbox',
    tag: 'plugins',
    summary: 'pluginのevent送信状況',
    access: PROJECT_ADMIN,
    responses: { 200: contract.pluginOutboxSummarySchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/plugins/:id/datasets/search',
    tag: 'plugins',
    summary: 'plugin側のDatasetを検索',
    access: PROJECT_ADMIN,
    body: pluginDatasetSearchSchema,
    responses: { 200: contract.itemsOf(contract.pluginDatasetSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/plugins/:id/datasets/import',
    tag: 'plugins',
    summary: 'plugin側のDatasetを参照として取り込む',
    access: PROJECT_ADMIN,
    body: pluginDatasetImportSchema,
    responses: { 201: contract.datasetVersionSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/plugins/:id/events/retry',
    tag: 'plugins',
    summary: '送れなかったeventを再送',
    access: PROJECT_ADMIN,
    responses: { 200: z.strictObject({ queued: z.number().int() }) },
  },

  // promotion
  {
    method: 'get',
    path: '/api/projects/:p/promotion-policies',
    tag: 'promotion',
    summary: '昇格policy一覧',
    access: PROJECT_VIEWER,
    query: promotionPolicyQuerySchema,
    responses: { 200: contract.itemsOf(contract.promotionPolicySchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/promotion-policies',
    tag: 'promotion',
    summary: '昇格policyを作成',
    access: PROJECT_ADMIN,
    body: promotionPolicyCreateSchema,
    responses: { 201: contract.promotionPolicySchema },
    errors: routeError(422, 'promotion_rule_not_evaluation'),
  },
  {
    method: 'patch',
    path: '/api/projects/:p/promotion-policies/:id',
    tag: 'promotion',
    summary: 'policyの有効・無効',
    access: PROJECT_ADMIN,
    body: promotionPolicyPatchSchema,
    responses: { 200: contract.promotionPolicySchema },
  },
  {
    method: 'put',
    path: '/api/projects/:p/promotion-policies/:id/owner',
    tag: 'promotion',
    summary: 'policyの所有者をService Accountへ移す',
    access: PROJECT_ADMIN,
    body: promotionPolicyOwnerSchema,
    responses: { 200: contract.promotionPolicySchema },
    errors: routeError(422, 'promotion_owner_invalid'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/promotion-evaluations',
    tag: 'promotion',
    summary: '昇格の判定履歴',
    access: PROJECT_VIEWER,
    query: promotionEvaluationQuerySchema,
    responses: { 200: contract.promotionEvaluationPageSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/promotion-evaluations/:id/reevaluate',
    tag: 'promotion',
    summary: '判定をやり直す',
    access: PROJECT_ADMIN,
    responses: { 201: contract.promotionEvaluationSchema },
  },

  // collaboration
  {
    method: 'get',
    path: '/api/projects/:p/comments',
    tag: 'collaboration',
    summary: 'コメント一覧',
    access: PROJECT_VIEWER,
    query: commentListQuerySchema,
    responses: { 200: contract.commentPageSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/comments',
    tag: 'collaboration',
    summary: 'コメントを投稿（tokenのscopeは対象の種類による）',
    access: RUNS_WRITE,
    body: commentCreateSchema,
    responses: { 201: contract.commentSchema },
    errors: [
      ...routeError(409, 'comment_target_deleted'),
      ...routeError(422, 'comment_parent_mismatch', 'comment_target_unsupported'),
    ],
  },
  {
    method: 'patch',
    path: '/api/projects/:p/comments/:c',
    tag: 'collaboration',
    summary: '自分のコメントを編集',
    access: RUNS_WRITE,
    body: commentUpdateSchema,
    responses: { 200: contract.commentSchema },
    errors: [...routeError(403, 'comment_author_required'), ...routeError(409, 'comment_deleted')],
  },
  {
    method: 'delete',
    path: '/api/projects/:p/comments/:c',
    tag: 'collaboration',
    summary: 'コメントを削除（作成者かProject admin）',
    access: RUNS_WRITE,
    responses: { 204: null },
    errors: routeError(403, 'comment_delete_forbidden'),
  },
  {
    method: 'get',
    path: '/api/projects/:p/saved-views',
    tag: 'saved-views',
    summary: '保存ビュー一覧',
    access: PROJECT_VIEWER,
    query: savedViewListQuerySchema,
    responses: { 200: contract.itemsOf(contract.savedViewSchema) },
  },
  {
    method: 'get',
    path: '/api/projects/:p/saved-views/:v',
    tag: 'saved-views',
    summary: '保存ビュー',
    access: PROJECT_VIEWER,
    responses: { 200: contract.savedViewSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/saved-views',
    tag: 'saved-views',
    summary: '保存ビューを作成（共有はeditor以上）',
    access: { kind: 'project', role: 'viewer', scope: 'runs:write' },
    body: savedViewCreateSchema,
    responses: { 201: contract.savedViewSchema },
    errors: [
      ...routeError(403, 'saved_view_share_forbidden'),
      ...routeError(409, 'saved_view_name_conflict'),
      ...routeError(
        422,
        'saved_view_experiment_not_found',
        'saved_view_filter_invalid',
        'saved_view_state_too_large',
        'saved_view_state_unsupported_version',
      ),
    ],
  },
  {
    method: 'patch',
    path: '/api/projects/:p/saved-views/:v',
    tag: 'saved-views',
    summary: '保存ビューを変更',
    access: { kind: 'project', role: 'viewer', scope: 'runs:write' },
    body: savedViewPatchSchema,
    responses: { 200: contract.savedViewSchema },
    errors: [
      ...routeError(403, 'saved_view_share_forbidden', 'saved_view_owner_required'),
      ...routeError(409, 'saved_view_name_conflict'),
      ...routeError(
        422,
        'saved_view_experiment_not_found',
        'saved_view_filter_invalid',
        'saved_view_state_too_large',
        'saved_view_state_unsupported_version',
      ),
    ],
  },
  {
    method: 'delete',
    path: '/api/projects/:p/saved-views/:v',
    tag: 'saved-views',
    summary: '保存ビューを削除',
    access: { kind: 'project', role: 'viewer', scope: 'runs:write' },
    responses: { 204: null },
    errors: routeError(403, 'saved_view_owner_required'),
  },

  // sync (offline Runs)
  {
    method: 'put',
    path: '/api/projects/:p/sync/runs/:r',
    tag: 'sync',
    summary: 'オフラインで記録したRunを作成（冪等）',
    access: RUNS_WRITE,
    body: syncRunCreateSchema,
    responses: { 200: contract.runSchema, 201: contract.runSchema },
    errors: [
      ...routeError(409, 'sync_run_conflict'),
      ...routeError(422, 'sync_timestamp_in_future', 'reserved_tag'),
    ],
  },
  {
    method: 'post',
    path: '/api/projects/:p/sync/runs/:r/batches',
    tag: 'sync',
    summary: '記録のbatchを送る（batchIdで冪等）',
    access: RUNS_WRITE,
    body: syncBatchSchema,
    maxBodyBytes: SYNC_BATCH_MAX_BYTES,
    responses: { 200: contract.syncBatchResultSchema },
    errors: [
      ...routeError(409, 'sync_param_conflict', 'sync_status_conflict', 'sync_run_conflict'),
      ...routeError(422, 'sync_ended_before_start', 'sync_timestamp_in_future'),
    ],
  },
  {
    method: 'post',
    path: '/api/projects/:p/sync/runs/:r/artifacts/check',
    tag: 'sync',
    summary: '保存済みのArtifactを確かめる',
    access: ARTIFACTS_WRITE,
    body: artifactPresenceCheckSchema,
    responses: { 200: contract.artifactPresenceSchema },
  },

  // checkpoints
  {
    method: 'get',
    path: '/api/projects/:p/runs/:r/checkpoints',
    tag: 'checkpoints',
    summary: 'Runのcheckpoint',
    access: PROJECT_VIEWER,
    query: runCheckpointListQuerySchema,
    responses: { 200: contract.itemsOf(contract.runCheckpointSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:p/runs/:r/checkpoints',
    tag: 'checkpoints',
    summary: 'checkpointを登録',
    access: RUNS_WRITE,
    body: runCheckpointCreateSchema,
    responses: { 201: contract.runCheckpointSchema },
    errors: [
      ...routeError(403, 'checkpoint_forbidden'),
      ...routeError(409, 'run_finalized', 'checkpoint_exists'),
      ...routeError(422, 'checkpoint_run_kind', 'checkpoint_artifact_run'),
    ],
  },

  // sweeps
  {
    method: 'get',
    path: '/api/projects/:p/sweeps',
    tag: 'sweeps',
    summary: 'Sweep一覧',
    access: PROJECT_VIEWER,
    query: sweepListQuerySchema,
    responses: { 200: contract.sweepPageSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/sweeps',
    tag: 'sweeps',
    summary: 'Sweepを作成。tokenにはjobs:writeも要る',
    access: RUNS_WRITE,
    body: sweepCreateSchema,
    responses: { 201: contract.sweepSchema },
    errors: routeError(
      422,
      'sweep_space_invalid',
      'sweep_early_terminate_invalid',
      'target_required',
    ),
  },
  {
    method: 'get',
    path: '/api/projects/:p/sweeps/:s',
    tag: 'sweeps',
    summary: 'Sweepの詳細',
    access: PROJECT_VIEWER,
    responses: { 200: contract.sweepSchema },
  },
  {
    method: 'patch',
    path: '/api/projects/:p/sweeps/:s',
    tag: 'sweeps',
    summary: '試行数・並列数を変更',
    access: JOBS_WRITE,
    body: sweepPatchSchema,
    responses: { 200: contract.sweepSchema },
    errors: [
      ...routeError(403, 'sweep_owner_required'),
      ...routeError(409, 'sweep_finished'),
      ...routeError(422, 'sweep_max_trials_below_created'),
    ],
  },
  {
    method: 'get',
    path: '/api/projects/:p/sweeps/:s/trials',
    tag: 'sweeps',
    summary: 'Sweepの試行',
    access: PROJECT_VIEWER,
    query: sweepTrialQuerySchema,
    responses: { 200: contract.sweepTrialPageSchema },
  },
  {
    method: 'post',
    path: '/api/projects/:p/sweeps/:s/pause',
    tag: 'sweeps',
    summary: 'Sweepを一時停止',
    access: JOBS_WRITE,
    responses: { 200: contract.sweepSchema },
    errors: [...routeError(403, 'sweep_owner_required'), ...routeError(409, 'sweep_finished')],
  },
  {
    method: 'post',
    path: '/api/projects/:p/sweeps/:s/resume',
    tag: 'sweeps',
    summary: 'Sweepを再開',
    access: JOBS_WRITE,
    responses: { 200: contract.sweepSchema },
    errors: [
      ...routeError(403, 'sweep_owner_required'),
      ...routeError(409, 'sweep_finished', 'task_revision_changed', 'sweep_owner_forbidden'),
    ],
  },
  {
    method: 'post',
    path: '/api/projects/:p/sweeps/:s/cancel',
    tag: 'sweeps',
    summary: 'Sweepを取り消す',
    access: JOBS_WRITE,
    body: sweepCancelSchema,
    responses: { 200: contract.sweepSchema },
    errors: [...routeError(403, 'sweep_owner_required'), ...routeError(409, 'sweep_finished')],
  },

  // administration
  {
    method: 'get',
    path: '/api/admin/storage-backends',
    tag: 'admin',
    summary: '保存先一覧',
    access: GLOBAL_ADMIN,
    responses: { 200: contract.itemsOf(contract.storageBackendSchema) },
  },
  {
    method: 'post',
    path: '/api/admin/storage-backends',
    tag: 'admin',
    summary: '保存先を登録（secretは画面へ返さない）',
    access: GLOBAL_ADMIN,
    body: storageBackendCreateSchema,
    responses: { 201: contract.storageBackendSchema },
    errors: [
      ...routeError(409, 'storage_backend_exists'),
      ...routeError(
        422,
        'invalid_storage_backend_config',
        'multipart_unsupported',
        'storage_credentials_incomplete',
        'storage_secret_key_missing',
      ),
    ],
  },
  {
    method: 'patch',
    path: '/api/admin/storage-backends/:name',
    tag: 'admin',
    summary: '保存先を変更・無効化',
    access: GLOBAL_ADMIN,
    body: storageBackendPatchSchema,
    responses: { 200: contract.storageBackendSchema },
    errors: [
      ...routeError(
        409,
        'storage_backend_in_use',
        'storage_backend_read_only',
        'storage_backend_is_default',
      ),
      ...routeError(
        422,
        'invalid_storage_backend_config',
        'storage_credentials_incomplete',
        'storage_secret_key_missing',
      ),
    ],
  },
  {
    method: 'post',
    path: '/api/admin/storage-backends/:name/test',
    tag: 'admin',
    summary: '保存先の接続テスト',
    access: GLOBAL_ADMIN,
    responses: { 200: contract.storageTestResultSchema },
  },
  {
    method: 'get',
    path: '/api/admin/storage-settings',
    tag: 'admin',
    summary: '既定の保存先',
    access: GLOBAL_ADMIN,
    responses: { 200: contract.storageSettingsSchema },
  },
  {
    method: 'put',
    path: '/api/admin/storage-settings',
    tag: 'admin',
    summary: '既定の保存先を変更',
    access: GLOBAL_ADMIN,
    body: storageSettingsUpdateSchema,
    responses: { 200: contract.storageSettingsSchema },
    errors: routeError(422, 'storage_backend_unavailable'),
  },
  {
    method: 'get',
    path: '/api/admin/users',
    tag: 'admin',
    summary: 'ユーザー一覧',
    access: { kind: 'globalAdmin', sessionOnly: true },
    query: adminUserQuerySchema,
    responses: { 200: contract.itemsOf(contract.adminUserSchema) },
  },
  {
    method: 'post',
    path: '/api/admin/users',
    tag: 'admin',
    summary: 'ローカルアカウントを作成',
    access: { kind: 'globalAdmin', sessionOnly: true },
    body: adminUserCreateSchema,
    responses: { 201: contract.adminUserSchema },
    errors: [...routeError(409, 'username_taken'), ...routeError(422, 'weak_password')],
  },
  {
    method: 'patch',
    path: '/api/admin/users/:id',
    tag: 'admin',
    summary: 'ユーザーを変更・無効化',
    access: { kind: 'globalAdmin', sessionOnly: true },
    body: adminUserPatchSchema,
    responses: { 200: contract.adminUserSchema },
    errors: [
      ...routeError(409, 'last_global_admin'),
      ...routeError(422, 'admin_role_managed_by_sso', 'service_account_admin_forbidden'),
    ],
  },
  {
    method: 'post',
    path: '/api/admin/users/:id/reset-password',
    tag: 'admin',
    summary: '一時passwordを発行',
    access: { kind: 'globalAdmin', sessionOnly: true },
    responses: { 200: contract.adminUserPasswordResetSchema },
    errors: routeError(422, 'local_account_required'),
  },

  // notifications
  {
    method: 'get',
    path: '/api/notification-channels',
    tag: 'notifications',
    summary: '通知先一覧',
    access: GLOBAL_ADMIN,
    responses: { 200: contract.itemsOf(contract.notificationChannelSchema) },
  },
  {
    method: 'post',
    path: '/api/notification-channels',
    tag: 'notifications',
    summary: '通知先を作成',
    access: GLOBAL_ADMIN,
    body: notificationChannelCreateSchema,
    responses: { 201: contract.notificationChannelSchema },
    errors: [
      ...routeError(409, 'notification_channel_exists'),
      ...routeError(422, 'notification_channel_invalid'),
    ],
  },
  {
    method: 'patch',
    path: '/api/notification-channels/:channelId',
    tag: 'notifications',
    summary: '通知先を変更',
    access: GLOBAL_ADMIN,
    body: notificationChannelPatchSchema,
    responses: { 200: contract.notificationChannelSchema },
    errors: [
      ...routeError(409, 'notification_channel_exists'),
      ...routeError(422, 'notification_channel_invalid'),
    ],
  },
  {
    method: 'post',
    path: '/api/notification-channels/:channelId/test',
    tag: 'notifications',
    summary: '通知先へテスト送信',
    access: GLOBAL_ADMIN,
    responses: { 200: contract.notificationTestResultSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:projectId/notification-channels',
    tag: 'notifications',
    summary: 'Projectで選べる通知先',
    access: PROJECT_ADMIN,
    responses: { 200: contract.itemsOf(contract.notificationChannelSchema) },
  },
  {
    method: 'get',
    path: '/api/projects/:projectId/notification-rules',
    tag: 'notifications',
    summary: '通知rule一覧',
    access: PROJECT_ADMIN,
    responses: { 200: contract.itemsOf(contract.notificationRuleSchema) },
  },
  {
    method: 'post',
    path: '/api/projects/:projectId/notification-rules',
    tag: 'notifications',
    summary: '通知ruleを作成',
    access: PROJECT_ADMIN,
    body: notificationRuleCreateSchema,
    responses: { 201: contract.notificationRuleSchema },
  },
  {
    method: 'patch',
    path: '/api/projects/:projectId/notification-rules/:ruleId',
    tag: 'notifications',
    summary: '通知ruleの有効・無効',
    access: PROJECT_ADMIN,
    body: notificationRulePatchSchema,
    responses: { 200: contract.notificationRuleSchema },
  },
  {
    method: 'get',
    path: '/api/projects/:projectId/notification-deliveries',
    tag: 'notifications',
    summary: '通知の送信履歴',
    access: PROJECT_ADMIN,
    query: notificationDeliveryQuerySchema,
    responses: { 200: contract.itemsOf(contract.notificationDeliverySchema) },
  },

  // operations
  {
    method: 'get',
    path: '/api/projects/:p/operations-alerts',
    tag: 'operations',
    summary: '運用アラート（Jobのheartbeat途絶・worker停止・plugin送信滞留）',
    access: PROJECT_VIEWER,
    query: operationsAlertQuerySchema,
    responses: { 200: contract.itemsOf(contract.operationsAlertSchema) },
  },
];
