import { z } from 'zod';
import { groupBySchema, keysSchema, xAxisSchema } from './metricSeries/metricSeriesValidation.js';

/** Width of the chart grid; ChartPanelLayout.columns is fixed to this value. */
const CHART_GRID_COLUMNS = 12;
// A page of charts beyond this is slower to draw than to split into another view or report.
export const MAX_CHART_PANELS = 100;
// Rows grow downwards without a fixed end; this only rejects values no layout produces.
const MAX_CHART_GRID_ROW = 10_000;
const MAX_CHART_PANEL_HEIGHT = 100;
// Panel IDs are generated by the Web client (UUIDs); the bound only rejects abuse.
const MAX_CHART_PANEL_ID_LENGTH = 100;
const MAX_CHART_PANEL_TITLE_LENGTH = 200;

const chartPanelGridCellSchema = z
  .strictObject({
    x: z
      .number()
      .int()
      .min(0)
      .max(CHART_GRID_COLUMNS - 1),
    y: z.number().int().min(0).max(MAX_CHART_GRID_ROW),
    w: z.number().int().min(1).max(CHART_GRID_COLUMNS),
    h: z.number().int().min(1).max(MAX_CHART_PANEL_HEIGHT),
  })
  .refine((cell) => cell.x + cell.w <= CHART_GRID_COLUMNS, 'panel exceeds the grid width');

export const chartPanelConfigSchema = z.strictObject({
  id: z.string().min(1).max(MAX_CHART_PANEL_ID_LENGTH),
  title: z.string().max(MAX_CHART_PANEL_TITLE_LENGTH).optional(),
  metricKeys: keysSchema,
  xAxis: xAxisSchema,
  yScale: z.enum(['linear', 'log']),
  smoothing: z.strictObject({
    kind: z.enum(['none', 'ema', 'gaussian', 'running_average']),
    weight: z.number().min(0).max(1),
  }),
  showRange: z.boolean(),
  groupBy: groupBySchema.optional(),
  layout: chartPanelGridCellSchema,
});

/** ChartPanelLayout (contracts/chartPanels.ts), shared by saved views and reports. */
export const chartPanelLayoutSchema = z.strictObject({
  version: z.literal(1),
  columns: z.literal(CHART_GRID_COLUMNS),
  panels: z
    .array(chartPanelConfigSchema)
    .max(MAX_CHART_PANELS)
    .refine(
      (panels) => new Set(panels.map((panel) => panel.id)).size === panels.length,
      'panel ids must be unique',
    ),
});
